package com.bussiness.awpl.utils

object AppConstant {
    val DOCTOR: String ="DOCTOR"
    val uid: String? ="uid"
    val CHANNEL_NAME: String?="channel_name"
    val AppoitmentId: String? ="appointment_id"
    val BOOK_MODEL: String? ="book_model"
    val ID: String? ="id"
    val FOR_ME: String? = "for_me"
    val OTHERS: String? ="others"
    val DISEASE_ID: String? ="disease_id"
    val DISEASE_LIST: String? ="disease_list"
    val Base_URL: String ="https://awplconnectadmin.tgastaging.com"
    val NAME: String? ="name"
    val AuthToken: String = "AUTH_TOKEN"
    val unKnownError = "There was an unknown error. Check your connection, and try again."
    val UserId ="user_id"
    var IMAGE ="IMAGE"
    var Age ="AGE"
    var Height ="height"
    var Weight ="weight"
    var FullName ="fullName"
    var Gender ="gender"
    var TYPE ="type"
    var DATE = "date"
    var TIME ="time"
    var APPID ="APPID"
    var EMAIL ="email"

}